module.exports = [
    {key:"  " , name:"Please select a country"},
    {key:"AF" , name:"Afghanistan"},
    {key:"AL" , name:"Albania"},
    {key:"DZ" , name:"Algeria"},
    {key:"AS" , name:"American Samoa"},
    {key:"AD" , name:"Andorra"},
    {key:"AO" , name:"Angola"},
    {key:"AI" , name:"Anguilla"},
    {key:"AQ" , name:"Antarctica"},
    {key:"AG" , name:"Antigua and Barbuda"},
    {key:"AR" , name:"Argentina"},
    {key:"AM" , name:"Armenia"},
    {key:"AW" , name:"Aruba"},
    {key:"AU" , name:"Australia"},
    {key:"AT" , name:"Austria"},
    {key:"AZ" , name:"Azerbaijan"},
    {key:"BS" , name:"Bahamas"},
    {key:"BH" , name:"Bahrain"},
    {key:"BD" , name:"Bangladesh"},
    {key:"BB" , name:"Barbados"},
    {key:"BY" , name:"Belarus"},
    {key:"BE" , name:"Belgium"},
    {key:"BZ" , name:"Belize"},
    {key:"BJ" , name:"Benin"},
    {key:"BM" , name:"Bermuda"},
    {key:"BT" , name:"Bhutan"},
    {key:"BO" , name:"Bolivia"},
    {key:"BA" , name:"Bosnia and Herzegowina"},
    {key:"BW" , name:"Botswana"},
    {key:"BV" , name:"Bouvet Island"},
    {key:"BR" , name:"Brazil"},
    {key:"IO" , name:"British Indian Ocean Territory"},
    {key:"BN" , name:"Brunei Darussalam"},
    {key:"BG" , name:"Bulgaria"},
    {key:"BF" , name:"Burkina Faso"}
]